// ---------------------------------------------------------------------------
// Seed data. Used by the local (browser) adapter to pre-populate the app, and
// it mirrors supabase/migrations/0002_seed.sql for the database backend.
// ---------------------------------------------------------------------------
import {
  AppSettings,
  Campaign,
  CapacitySource,
  CostItem,
  DEFAULT_SETTINGS,
  Domain,
  Lead,
  LeadList,
  SetupPlaybook,
  SetupStep,
  TriState,
} from "./types";

const now = new Date().toISOString();

export const CAMPAIGN_IDS = {
  aeo: "11111111-1111-4111-8111-111111111111",
  cbd: "22222222-2222-4222-8222-222222222222",
  backlink: "33333333-3333-4333-8333-333333333333",
};

export const SETUP_ID = "44444444-4444-4444-8444-444444444444";

export const seedCampaigns: Campaign[] = [
  {
    id: CAMPAIGN_IDS.aeo,
    name: "AEO Campaign",
    type: "AEO",
    description: "Answer Engine Optimization outreach.",
    color: "#FF90E8",
    status: "active",
    created_at: now,
  },
  {
    id: CAMPAIGN_IDS.cbd,
    name: "CBD Campaign",
    type: "CBD",
    description: "CBD niche outreach.",
    color: "#23A094",
    status: "active",
    created_at: now,
  },
  {
    id: CAMPAIGN_IDS.backlink,
    name: "Backlink Campaign",
    type: "Backlink",
    description: "Backlink / link-building outreach.",
    color: "#90A8ED",
    status: "active",
    created_at: now,
  },
];

interface DomainSeed {
  pos: number;
  domain: string;
  expiry: string;
  campaign: keyof typeof CAMPAIGN_IDS;
  campaignLabel: string;
  instantly: TriState;
  gmail: TriState;
  forwardedTo: string;
}

const domainSeeds: DomainSeed[] = [
  { pos: 1, domain: "aeoagency.cloud", expiry: "2027-02-13", campaign: "aeo", campaignLabel: "AEO Campaign", instantly: "Yes", gmail: "Yes", forwardedTo: "webofpicasso2@gmail.com" },
  { pos: 2, domain: "aeoagency.info", expiry: "2027-02-13", campaign: "aeo", campaignLabel: "AEO Campaign", instantly: "Yes", gmail: "Yes", forwardedTo: "webofpicasso2@gmail.com" },
  { pos: 3, domain: "aeoagency.online", expiry: "2027-02-14", campaign: "aeo", campaignLabel: "AEO Campaign", instantly: "Yes", gmail: "Yes", forwardedTo: "webofpicasso2@gmail.com" },
  { pos: 4, domain: "aeoagency.website", expiry: "2027-02-14", campaign: "aeo", campaignLabel: "AEO Campaign", instantly: "Yes", gmail: "Yes", forwardedTo: "webofpicasso2@gmail.com" },
  { pos: 5, domain: "theaeoagency.info", expiry: "2027-02-13", campaign: "aeo", campaignLabel: "AEO Campaign", instantly: "Yes", gmail: "Yes", forwardedTo: "webofpicasso2@gmail.com" },
  { pos: 6, domain: "theaeoagency.online", expiry: "2027-02-14", campaign: "aeo", campaignLabel: "AEO Campaign", instantly: "Yes", gmail: "Yes", forwardedTo: "webofpicasso2@gmail.com" },
  { pos: 7, domain: "buildwithwop.info", expiry: "2027-06-09", campaign: "aeo", campaignLabel: "AEO Campaign", instantly: "Yes", gmail: "Yes", forwardedTo: "webofpicasso2@gmail.com" },
  { pos: 8, domain: "rankwithwop.info", expiry: "2027-06-09", campaign: "aeo", campaignLabel: "AEO Campaign", instantly: "Yes", gmail: "Yes", forwardedTo: "webofpicasso2@gmail.com" },
  { pos: 9, domain: "rankwithwop.online", expiry: "2027-06-09", campaign: "aeo", campaignLabel: "AEO Campaign", instantly: "Partially", gmail: "Yes", forwardedTo: "webofpicasso2@gmail.com" },
  { pos: 10, domain: "risewithwop.info", expiry: "2027-06-09", campaign: "cbd", campaignLabel: "CBD Campaign", instantly: "Yes", gmail: "Yes", forwardedTo: "webofpicasso2@gmail.com" },
  { pos: 11, domain: "scalewithwop.info", expiry: "2027-06-09", campaign: "cbd", campaignLabel: "CBD Campaign", instantly: "Yes", gmail: "Yes", forwardedTo: "webofpicasso2@gmail.com" },
  { pos: 12, domain: "webofpicassoagency.info", expiry: "2027-06-09", campaign: "cbd", campaignLabel: "CBD Campaign", instantly: "Yes", gmail: "Yes", forwardedTo: "webofpicasso2@gmail.com" },
  { pos: 13, domain: "webofpicassoagency.online", expiry: "2027-06-09", campaign: "cbd", campaignLabel: "CBD Campaign", instantly: "Yes", gmail: "Yes", forwardedTo: "webofpicasso2@gmail.com" },
  { pos: 14, domain: "webofpicassodigital.info", expiry: "2027-06-09", campaign: "cbd", campaignLabel: "CBD Campaign", instantly: "Yes", gmail: "Yes", forwardedTo: "webofpicasso2@gmail.com" },
  { pos: 15, domain: "webofpicassodigital.online", expiry: "2027-06-09", campaign: "cbd", campaignLabel: "CBD Campaign", instantly: "Yes", gmail: "Yes", forwardedTo: "webofpicasso2@gmail.com" },
  { pos: 16, domain: "webofpicassoseo.info", expiry: "2027-06-09", campaign: "cbd", campaignLabel: "CBD Campaign", instantly: "Yes", gmail: "Yes", forwardedTo: "webofpicasso2@gmail.com" },
  { pos: 17, domain: "winwithwop.info", expiry: "2027-06-09", campaign: "backlink", campaignLabel: "Backlink Campaign", instantly: "Yes", gmail: "NA", forwardedTo: "rishi@webofpicasso.com" },
  { pos: 18, domain: "wopagency.info", expiry: "2027-06-09", campaign: "backlink", campaignLabel: "Backlink Campaign", instantly: "Yes", gmail: "NA", forwardedTo: "rishi@webofpicasso.com" },
  { pos: 19, domain: "wopmarketing.info", expiry: "2027-06-09", campaign: "backlink", campaignLabel: "Backlink Campaign", instantly: "Yes", gmail: "NA", forwardedTo: "rishi@webofpicasso.com" },
  { pos: 20, domain: "wopseo.info", expiry: "2027-06-09", campaign: "backlink", campaignLabel: "Backlink Campaign", instantly: "Yes", gmail: "NA", forwardedTo: "rishi@webofpicasso.com" },
];

export const seedDomains: Domain[] = domainSeeds.map((d) => ({
  id: `domain-${String(d.pos).padStart(2, "0")}-0000-4000-8000-000000000000`,
  position: d.pos,
  domain_name: d.domain,
  email_1: `tanuj@${d.domain}`,
  email_2: `tanuj.s@${d.domain}`,
  expiry_date: d.expiry,
  expiry_source: "manual",
  expiry_checked_at: null,
  domain_provider: "IONOS",
  mailing_server: "Amazon SES",
  mailing_status: "Yes",
  dns_provider: "Cloudflare",
  dns_status: "Yes",
  email_forward: "Cloudflare",
  hosting_provider: "Netlify",
  hosting_account: "git login - tanuj9825",
  website_note: "Netlify account git login - tanuj9825",
  emails_forwarded_to: d.forwardedTo,
  campaign_id: CAMPAIGN_IDS[d.campaign],
  campaign_label: d.campaignLabel,
  gravatar: "",
  gmail_send_configured: d.gmail,
  connected_to_instantly: d.instantly,
  warmup_started: "Yes",
  mailbox_daily_limit: null,
  renewal_cost: 12,
  notes: "",
  custom: {},
  created_at: now,
}));

export const seedCapacity: CapacitySource[] = [
  {
    id: "cap-ses-0000-4000-8000-000000000001",
    name: "Amazon SES",
    kind: "sending",
    limit_amount: 50000,
    limit_period: "day",
    used_amount: 0,
    color: "#FF9900",
    notes: "Production access. 50,000 emails / 24h, 14 emails/sec max send rate.",
    enabled: true,
    sort: 1,
  },
  {
    id: "cap-inst-0000-4000-8000-00000000002",
    name: "Instantly (Hyper Growth)",
    kind: "sending",
    limit_amount: 125000,
    limit_period: "month",
    used_amount: 0,
    color: "#3F6BFF",
    notes: "Hyper Growth plan, $97/mo. Renews Jul 8, 2026.",
    enabled: true,
    sort: 2,
  },
  {
    id: "cap-inst-0000-4000-8000-00000000003",
    name: "Instantly Contacts",
    kind: "contacts",
    limit_amount: 25000,
    limit_period: "month",
    used_amount: 948,
    color: "#B23386",
    notes: "Total uploaded contacts cap on the Hyper Growth plan.",
    enabled: true,
    sort: 3,
  },
];

export const seedCosts: CostItem[] = [
  {
    id: "cost-0000-0000-4000-8000-000000000001",
    name: "Domains (IONOS) × 20",
    category: "Domains",
    provider: "IONOS",
    amount: 12,
    currency: "USD",
    billing_cycle: "annual",
    quantity: 20,
    renews_on: "2027-06-09",
    notes: "Per-domain annual renewal (avg). Adjust per TLD.",
    active: true,
  },
  {
    id: "cost-0000-0000-4000-8000-000000000002",
    name: "Instantly — Hyper Growth",
    category: "Tools",
    provider: "Instantly",
    amount: 97,
    currency: "USD",
    billing_cycle: "monthly",
    quantity: 1,
    renews_on: "2026-07-08",
    notes: "25,000 contacts / 125,000 emails per month.",
    active: true,
  },
  {
    id: "cost-0000-0000-4000-8000-000000000003",
    name: "Amazon SES sending",
    category: "Sending",
    provider: "Amazon SES",
    amount: 0.1,
    currency: "USD",
    billing_cycle: "per-1000-emails",
    quantity: 1,
    renews_on: null,
    notes: "$0.10 per 1,000 emails sent.",
    active: true,
  },
  {
    id: "cost-0000-0000-4000-8000-000000000004",
    name: "Netlify (site hosting)",
    category: "Hosting",
    provider: "Netlify",
    amount: 0,
    currency: "USD",
    billing_cycle: "monthly",
    quantity: 1,
    renews_on: null,
    notes: "Free tier for campaign sites (account: tanuj9825).",
    active: true,
  },
  {
    id: "cost-0000-0000-4000-8000-000000000005",
    name: "Cloudflare (DNS + Email Routing)",
    category: "Email Infrastructure",
    provider: "Cloudflare",
    amount: 0,
    currency: "USD",
    billing_cycle: "monthly",
    quantity: 1,
    renews_on: null,
    notes: "Free DNS + email forwarding.",
    active: true,
  },
  {
    id: "cost-0000-0000-4000-8000-000000000006",
    name: "OpenAI (lead enrichment)",
    category: "AI",
    provider: "OpenAI",
    amount: 0,
    currency: "USD",
    billing_cycle: "monthly",
    quantity: 1,
    renews_on: null,
    notes: "Usage-based. Set an estimated monthly spend.",
    active: true,
  },
];

export const seedSetups: SetupPlaybook[] = [
  {
    id: SETUP_ID,
    name: "Current Cold Email Setup — 2026",
    date: "2026-02-10",
    summary:
      "20 domains on IONOS, DNS + email forwarding on Cloudflare, Amazon SES as the mailing server, campaign sites on Netlify (account tanuj9825), Gmail send-as for replies, mailboxes connected to Instantly (Hyper Growth) with warmup enabled.",
    status: "active",
    created_at: now,
  },
];

export const seedSetupSteps: SetupStep[] = [
  {
    id: "step-0000-0000-4000-8000-000000000001",
    setup_id: SETUP_ID,
    position: 1,
    title: "Bought the domains",
    category: "Domains",
    platform: "IONOS",
    account_used: "IONOS account",
    details:
      "Registered 20 domains across .info / .online / .cloud / .website TLDs. Two name patterns: aeoagency*, *withwop, webofpicasso*. Renewal handled per-domain.",
    links: [{ label: "IONOS dashboard", url: "https://www.ionos.com/" }],
    done: true,
  },
  {
    id: "step-0000-0000-4000-8000-000000000002",
    setup_id: SETUP_ID,
    position: 2,
    title: "Pointed DNS to Cloudflare",
    category: "DNS",
    platform: "Cloudflare",
    account_used: "Cloudflare account",
    details:
      "Added each domain to Cloudflare and switched IONOS nameservers to Cloudflare. Manage all MX / SPF / DKIM / DMARC records here.",
    links: [{ label: "Cloudflare dashboard", url: "https://dash.cloudflare.com/" }],
    done: true,
  },
  {
    id: "step-0000-0000-4000-8000-000000000003",
    setup_id: SETUP_ID,
    position: 3,
    title: "Set up Amazon SES (mailing server)",
    category: "Email Server",
    platform: "Amazon SES",
    account_used: "AWS account",
    details:
      "Verified each domain in SES, published DKIM CNAMEs + SPF + DMARC via Cloudflare, requested production access. Daily quota 50,000 emails / 24h.",
    links: [{ label: "SES console", url: "https://console.aws.amazon.com/ses/" }],
    done: true,
  },
  {
    id: "step-0000-0000-4000-8000-000000000004",
    setup_id: SETUP_ID,
    position: 4,
    title: "Set up email forwarding",
    category: "Forwarding",
    platform: "Cloudflare Email Routing",
    account_used: "Cloudflare account",
    details:
      "Cloudflare Email Routing forwards inbound mail. AEO + CBD domains forward to webofpicasso2@gmail.com; Backlink domains forward to rishi@webofpicasso.com.",
    links: [{ label: "Email Routing", url: "https://dash.cloudflare.com/" }],
    done: true,
  },
  {
    id: "step-0000-0000-4000-8000-000000000005",
    setup_id: SETUP_ID,
    position: 5,
    title: "Built the campaign sites",
    category: "Sites",
    platform: "Netlify",
    account_used: "Netlify (git login: tanuj9825)",
    details:
      "Each domain has a simple site deployed on Netlify under the tanuj9825 account so the domain resolves to a real website (improves deliverability).",
    links: [{ label: "Netlify dashboard", url: "https://app.netlify.com/" }],
    done: true,
  },
  {
    id: "step-0000-0000-4000-8000-000000000006",
    setup_id: SETUP_ID,
    position: 6,
    title: "Configured Gmail 'Send As'",
    category: "Gmail",
    platform: "Gmail",
    account_used: "webofpicasso2@gmail.com",
    details:
      "Added each mailbox as a 'Send mail as' identity in Gmail using SES SMTP credentials, so replies can be handled from Gmail. (Backlink domains: N/A.)",
    links: [{ label: "Gmail settings", url: "https://mail.google.com/mail/u/0/#settings/accounts" }],
    done: true,
  },
  {
    id: "step-0000-0000-4000-8000-000000000007",
    setup_id: SETUP_ID,
    position: 7,
    title: "Connected mailboxes to Instantly",
    category: "Sending Tool",
    platform: "Instantly",
    account_used: "Instantly (Hyper Growth)",
    details:
      "Connected all sending mailboxes to Instantly via SMTP/IMAP for campaign sending and rotation. Plan caps: 25,000 contacts / 125,000 emails per month.",
    links: [{ label: "Instantly", url: "https://app.instantly.ai/" }],
    done: true,
  },
  {
    id: "step-0000-0000-4000-8000-000000000008",
    setup_id: SETUP_ID,
    position: 8,
    title: "Started warmup",
    category: "Warmup",
    platform: "Instantly",
    account_used: "Instantly (Hyper Growth)",
    details:
      "Enabled warmup on every mailbox to build sender reputation before scaling sends. Ramp gradually toward the per-inbox daily target.",
    links: [{ label: "Instantly warmup", url: "https://app.instantly.ai/" }],
    done: true,
  },
];

export const seedLeadLists: LeadList[] = [
  {
    id: "list-0000-0000-4000-8000-000000000001",
    name: "Master — Scraped Leads",
    parent_id: null,
    description: "All raw scraped leads land here before filtering.",
    color: "#FF90E8",
    source: "Apollo / scrape",
    created_at: now,
  },
  {
    id: "list-0000-0000-4000-8000-000000000002",
    name: "AEO — Qualified",
    parent_id: "list-0000-0000-4000-8000-000000000001",
    description: "Sub-list filtered for the AEO campaign.",
    color: "#23A094",
    source: "Filtered from master",
    created_at: now,
  },
];

export const seedLeads: Lead[] = [
  {
    id: "lead-0000-0000-4000-8000-000000000001",
    list_id: "list-0000-0000-4000-8000-000000000001",
    email: "jane@acmeco.com",
    first_name: "Jane",
    last_name: "Doe",
    company: "Acme Co",
    title: "Head of Marketing",
    website: "acmeco.com",
    linkedin: "https://linkedin.com/in/janedoe",
    phone: "",
    location: "Austin, TX",
    industry: "SaaS",
    employees: "51-200",
    status: "new",
    used_in_campaign_id: null,
    used_at: null,
    enriched: false,
    category: "",
    relevance: "",
    discarded: false,
    discarded_at: null,
    score: 72,
    tags: ["inbound-fit"],
    enrichment: {},
    custom: {},
    created_at: now,
  },
  {
    id: "lead-0000-0000-4000-8000-000000000002",
    list_id: "list-0000-0000-4000-8000-000000000001",
    email: "mark@brightlabs.io",
    first_name: "Mark",
    last_name: "Lee",
    company: "Bright Labs",
    title: "Founder",
    website: "brightlabs.io",
    linkedin: "",
    phone: "",
    location: "Remote",
    industry: "Agency",
    employees: "1-10",
    status: "used",
    used_in_campaign_id: CAMPAIGN_IDS.aeo,
    used_at: now,
    enriched: true,
    category: "Agency",
    relevance: "relevant",
    discarded: false,
    discarded_at: null,
    score: 65,
    tags: ["agency"],
    enrichment: { summary: "Boutique SEO agency, good ICP match." },
    custom: {},
    created_at: now,
  },
];

export const seedSettings: AppSettings = { ...DEFAULT_SETTINGS };
